version: '3'
services:
  web:
    image: nginx:latest
    volumes:
    - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
    - ".:/var/www/html"
    - "./logs:/var/log/nginx"
    ports:
    - "4201:80"
    restart: always
    depends_on:
    - php
    - db
  php:
    image: php7.2-fpm__prod:latest
    restart: always
    volumes:
    - ".:/var/www/html"
    depends_on:
    - memcached
  pgsql_db:
    image: postgres
    restart: always
    volumes:
    - "./database/pgsql:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: pgpwdd
    ports:
    - "5432:5432"
  db:
    image: mysql:latest
    volumes:
    - "./database/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwds
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: far
      MYSQL_PASSWORD: pwdffar
    ports:
    - "3306:3306"
  memcached:
    image: memcached
    restart: always
